# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink: /blog/:title

# Setup
title:		Ryan Cohen
tagline:	'blog'
description:	'My blog
url:		http://imryan.net

author:
  name:	‘Ryan ‘Cohen
  url:	https://twitter.com/imryan

paginate:	6

# Custom vars
icon: /assets/images/icon.png
cover: /assets/images/cover.jpg
version:	1.0.0
github:
  repo:	https://github.com/imryan
copyright: <p class="copyright">&copy;2014, <a href="http://camporez.com" target="_blank">Camporez</a>. <a href="http://creativecommons.org/licenses/by-nc/2.5/br/" target="_blank">Some rights reserved</a>.</p>
