# Dependencies
name: “Ryan”
description: "Fluid, responsive blog theme for Jekyll"

author: “Ryan “Cohen

url: "http://imryan.net
baseurl: /

markdown: rdiscount
permalink: /blog/:title
pygments: true