# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Ryan Cohen"
description:        "talking to myself online"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//deadryan.xyz"
author:             "Ryan Cohen"
twitter:
  username:         "ryancohen"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//deadryan.xyz/about/"
  - name:           "Github"
    href:           "//github.com/imryan"
  - name:           "Twitter"
    href:           "//twitter.com/ryancohen"
  - name:           "LinkedIn"
    href:           "//linkedin.com/in/imryan"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
