# Setup
title:               Ryan Cohen
tagline:             'on the web'
description:         'My webspot'
url:                 http://deadryan.xyz
baseurl:             'deadryan.xyz'
paginate:            5

# About/contact
author:
  name:              Ryan Cohen
  url:               https://twitter.com/ryancohen
  email:             notryancohen@gmail.com

# Custom vars
version:             1.0.0
