name: "Ryan"
description: "Developer."

author: "Ryan Cohen"

url: "http://imryan.net"
baseurl: /

markdown: rdiscount
permalink: /blog/:title
pygments: true

# Google Analytics
ga_domain: m3xm.github.io
ga_tracking_id: UA-47727049-1
